services:
  # --- LIGHTWEIGHT STREAMING NODE (ORACLE FREE TIER) ---
  streamer:
    build:
      context: .
      dockerfile: Dockerfile.streamer
    container_name: vartapravah_stream_oracle
    restart: always
    env_file: .env
    ports:
      - "1935:1935"
      - "8085:8080"
    volumes:
      - ./output:/home/ubuntu/videos
      - ./queue:/home/ubuntu/queue
      - ./logs:/home/ubuntu/logs
      - ./streamer/assets:/app/assets
      - ./streamer/assets:/app/app/assets
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
