version: "3.9"

services:
  # The Heavy Node (AI Processing)
  app:
    build: .
    container_name: vartapravah_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: vartapravah_ai_worker
    command: python app/workers/queue_worker.py
    restart: always
    env_file: .env
    depends_on:
      - redis

  sadtalker:
    build:
      context: .
      dockerfile: Dockerfile.sadtalker
    container_name: sadtalker
    restart: always
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - redis

  scheduler:
    build: .
    container_name: vartapravah_scheduler
    command: python app/scheduler/scheduler.py
    restart: always
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: vartapravah_redis
    restart: always
    ports:
      - "6379:6379" # Accessible by Oracle node
