services:
  # --- LIGHTWEIGHT STREAMING NODE ---
  streamer:
    build: ./streamer
    container_name: vartapravah_stream
    restart: always
    env_file: .env
    volumes:
      # This points to the SSHFS mount we set up
      - ./output:/app/videos 

  dashboard:
    build: ./app
    container_name: vartapravah_dashboard
    command: uvicorn main:app --host 0.0.0.0 --port 80
    restart: always
    ports:
      - "8888:80"
    env_file: .env
